package main

import (
	"log"
	"os"
	"path"
)

const (
	checkFunc        = "_go2check"
	handleBool       = "_go2handle"
	handleErr        = "_go2handleErr"
	varPrefix        = "_go2"
	extension        = ".go2"
	generatedComment = "// generated by go2gen; DO NOT EDIT"
)

func main() {
	var dir string
	var err error
	if len(os.Args) > 1 {
		dir = os.Args[1]
	} else {
		dir, err = os.Getwd()
		if err != nil {
			log.Fatal(err)
		}
	}
	err = generate(dir)
	if err != nil {
		log.Fatal(err)
	}
}

func generate(dir string) error {
	pkg, err := parsePkg(dir)
	if err != nil {
		return err
	}

	err = transform(pkg)
	if err != nil {
		return err
	}

	for _, gf := range pkg.go2Files {
		w, err := os.Create(path.Join(dir, gf.name) + ".go")
		if err != nil {
			return err
		}
		_, err = w.WriteString(generatedComment + "\n\n")
		if err != nil {
			return err
		}
		str, err := gf.string()
		if err != nil {
			return err
		}
		_, err = w.WriteString(str)
		if err != nil {
			return err
		}
	}

	return nil
}
