// generated by go2gen; DO NOT EDIT

package test

import (
	"fmt"
	"strconv"
)

func printSum1(a, b string) error {
	_go2int0, _go2error0 := strconv.Atoi(a)
	if _go2error0 != nil {
		return _go2error0
	}
	x := _go2int0
	_go2int1, _go2error1 := strconv.Atoi(b)
	if _go2error1 != nil {
		return _go2error1
	}
	y := _go2int1
	fmt.Println("result:", x+y)
	return nil
}

func printSum2(a, b string) error {
	_go2int0, _go2error0 := strconv.Atoi(a)
	if _go2error0 != nil {
		return _go2error0
	}
	_go2int1, _go2error1 := strconv.Atoi(b)
	if _go2error1 != nil {
		return _go2error1
	}
	fmt.Println("result:", _go2int0+_go2int1)
	return nil
}

func printSum3(a, b string) error {
	_go2int0, _go2error0 := strconv.Atoi(a)
	if _go2error0 != nil {
		return fmt.Errorf("printSum(%q + %q): %v", a, b, _go2error0)
	}
	x := _go2int0
	_go2int1, _go2error1 := strconv.Atoi(b)
	if _go2error1 != nil {
		return fmt.Errorf("printSum(%q + %q): %v", a, b, _go2error1)
	}
	y := _go2int1
	fmt.Println("result:", x+y)
	return nil
}

func printSum4(a, b string) error {
	_go2int0, _go2error0 := strconv.Atoi(a)
	if _go2error0 != nil {
		return _go2error0
	}
	x := _go2int0
	_go2int1, _go2error1 := strconv.Atoi(b)
	if _go2error1 != nil {
		return _go2error1
	}
	y := _go2int1
	fmt.Println("result:", x+y)
	return nil
}
