// generated by go2gen; DO NOT EDIT

package test

import (
	"fmt"
)

func something() error {
	return nil
}

func somethingElse() error {
	return nil
}

func do(e error) error {
	return e
}

func moreWrapping(e error) error {
	return e
}

func process(user string, files chan string) (n int, err error) {
	for i := 0; i < 3; i++ {
		_go2error0 := do(something())
		if _go2error0 != nil {
			_go2error0 = moreWrapping(_go2error0)
			_go2error0 = fmt.Errorf("attempt %d: %v", i, _go2error0)
			return 0, fmt.Errorf("process: %v", _go2error0)
		}
	}
	_go2error0 := do(somethingElse())
	if _go2error0 != nil {
		return 0, fmt.Errorf("process: %v", _go2error0)
	}
	return
}
