// generated by go2gen; DO NOT EDIT

package test

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"sort"
)

func SortContents(w io.Writer, files []string) error {
	lines := []string{}
	for _, file := range files {
		_go2ptrFile0, _go2error0 := os.Open(file)
		if _go2error0 != nil {
			return fmt.Errorf("read %s: %v ", file, _go2error0)
		}
		scan := bufio.NewScanner(_go2ptrFile0)
		for scan.Scan() {
			lines = append(lines, scan.Text())
		}
		_go2error1 := scan.Err()
		if _go2error1 != nil {
			return fmt.Errorf("read %s: %v ", file, _go2error1)
		}
	}
	sort.Strings(lines)
	for _, line := range lines {
		_, _go2error0 := io.WriteString(w, line)
		if _go2error0 != nil {
			return fmt.Errorf("process: %v", _go2error0)
		}
	}
	return nil
}
