// generated by go2gen; DO NOT EDIT

package test

import (
	"testing"
)

var testCases []testCase

type testCase struct {
	a string
	b string
}

func Foo(s string) (int, error) {
	return 0, nil
}

func TestFoo(t *testing.T) {
	for _, tc := range testCases {
		_go2int0, _go2error0 := Foo(tc.a)
		if _go2error0 != nil {
			t.Fatal(_go2error0)
		}
		x := _go2int0
		_go2int1, _go2error1 := Foo(tc.b)
		if _go2error1 != nil {
			t.Fatal(_go2error1)
		}
		y := _go2int1
		if x != y {
			t.Errorf("Foo(%v) != Foo(%v)", tc.a, tc.b)
		}
	}
}
