// generated by go2gen; DO NOT EDIT

package test

import (
	"io/ioutil"
)

func ReturnStmt() []byte {
	_go2slcByte0, _go2error0 := ioutil.ReadFile("path")
	if _go2error0 != nil {
		panic(_go2error0)
	}
	return _go2slcByte0
}
